### ISSUE TITLE
[NPC] Mottled Boar

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Anachronos#1]
So the Mottled Boar you should kill for the starter quest Cutting Teeth (ORC) is aggroing you when you have aggroed another.

In other words, I aggro one Boar, and if I go near another boar it targets and attacks me.

**Comment by Anthonhed** [comment]
After checking Retail I can confirm that this DOES NOT happen in retail

**Comment by Anthonhed** [comment]
Scorpid Worker http://www.wowhead.com/npc=3124/scorpid-worker
Northwatch Scout http://www.wowhead.com/npc=39317/northwatch-scout 
Mottled Boar http://www.wowhead.com/npc=3098/mottled-boar

**Comment by fvicaria** [comment]
Fixed. There may be more in other areas so just reopen this one when found.

**Comment by Anthonhed** [comment]
[Felstalker](http://www.wowhead.com/npc=3102/felstalker) Same issue
