### ISSUE TITLE
[Client]

### ISSUE THREAD

**Issue by flumby** [WoWManiaUK/Anachronos#37]
After making the wow directory not read only. You are given a different error which can be seen here:

https://cdn.discordapp.com/attachments/407571856837705749/414048351072550912/unknown.png

Kind Regards

Flumby

**Comment by fvicaria** [comment]
This is your responsibility.
Move it to the root drive.

**Comment by flumby** [comment]
It is at the root of my drive just like the wotlk wow mani.

**Comment by flumby** [comment]
![image](https://user-images.githubusercontent.com/36037370/36312448-7b8a379a-1326-11e8-8ea6-dcc79eed3098.png)
