### ISSUE TITLE
[Quest] [Spell] Primal Strike

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Anachronos#6]
Shamans reaching level 3 should learn the spell http://www.wowhead.com/spell=73899/primal-strike#screenshots At level 3 I learnt flame shot making it so I cannot do the quest.

**Comment by GMWeeble** [comment]
Primal strike is not even in my spell book.

**Comment by fvicaria** [comment]
I don't understand.  There should not be a quest it's deprecated. You should just learn.
Can you explain exactly what happened?

**Comment by GMWeeble** [comment]
When I got to level 2 I got a quest to reach level 3 and then I would learn the spell and to "Pratice" 3 primal strikes. Never got the spell at level 3.

**Comment by fvicaria** [comment]
Description: Primal Strike incorrectly offered by Meela Dawnstrider (3062) in Camp Narache.

Current behaviour: (Tell us what happens.) Meela Dawnstrider offers the player the quest Primal Strike to complete, but in Legion, Shaman players can't learn Primal Strike.

I will remove the quest.
