### ISSUE TITLE
missing NPC 42308 lieutenant horatio laine

### ISSUE THREAD

**Issue by xPUNJABx** [WoWManiaUK/Anachronos#8]
quest http://www.wowhead.com/quest=26378/heros-call-westfall and 
quest http://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me require the above missing npc.

**Comment by fvicaria** [comment]
NPC is there. Check conditions and pre-quests. You may have missed something.

![image](https://user-images.githubusercontent.com/9414661/33445746-bcbdac60-d5f5-11e7-83a1-73b7fd20c451.png)
